name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # THÊM BƯỚC NÀY ĐỂ CÀI ĐẶT THƯ VIỆN
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PHANMEMCUATOI_270195 }}
          channelId: live
          projectId: phanmemcuatoi-270195

          # Thêm dòng này để khớp với cấu hình trong firebase.json
          entryPoint: .
          # Đây là chỗ quan trọng nhất:
          public: dist/web